name: Callee Job
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo called!
